# Setup
title:               lirtha
tagline:             ''
description:         ''
url:                 http://lirtha.github.io
baseurl:             ''
paginate:            1
paginate_path:       '/blog/:num'
permalink:           pretty

# About/contact
author:
  name:              Seungwoo Kang
  url:               ''
  email:             lirtha@naver.com

# Gems
# plugins:
#   - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-80WW3TSXD0
